---
title: "Harmful Weather Events in the U.S. (1950-2011)"
author: "Pedro Córdova"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Synopsis



```{r}
if(!dir.exists("Data")) {dir.create("Data")}

download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2",
              "./Data/stormData.bz2", method = "curl")

library(knitr)
library(data.table)

stormData <- fread("./Data/stormData.bz2",
                               select = c(7,8,23:28),
                               col.names = c("State",
                                             "Event",
                                             "Fatalities",
                                             "Injuries",
                                             "propDamage",
                                             "propUnits",
                                             "cropDamage",
                                             "cropUnits"))
```
```{r}

```

## Data Processing

National Weather Service Storm Data Documentation [download this file]("https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf")

```{r data}

```



# Results